<?php
/**
* @file
* This module generates an Agegate (age verification) which prompts a visitor
* for their age. If they are of legal drinking age then the Agegate will deposit
* a cookie in the browser.
*
* This was developed by Nazario A. Ayala (Niztech) On Febuary 14th, 2013
*/

define('SHOW', 1);
define('HIDE', 0);

define('DECODED', 1);
define('ENCODED', 0);

define('YES', 1);
define('NO', 0);

/**
* hook_preprocess_page()
*/
function agegate_preprocess_page(&$vars){
  // generate settings array for agegate
  $display = true;
  $enviroment = 'live';

  if(isset($_SERVER['PANTHEON_ENVIRONMENT'])){
    $enviroment = $_SERVER['PANTHEON_ENVIRONMENT'];

    switch ($enviroment){
      case 'dev':
      if(variable_get('agegate_show') == HIDE){
        $display = false;
      }
      break;

      case 'test':
      if(variable_get('agegate_show') == HIDE){
        $display = false;
      }
      break;

      case 'live' :
      $display = true;
      break;
    }
  }
  else{
    if(variable_get('agegate_show') == HIDE){
      $display = false;
    }
  }

  $display = (user_access('administrator') == YES) ? false : $display;

  $settings = array(
    'debugmode'   => variable_get('agegate_debugmode'),
    'cookiedomain'=> variable_get('agegate_cookiedomain'),
    'cookiename'  => variable_get('agegate_cookiename'),
    'sitename'    => variable_get('agegate_sitename'),
    'sitemessage' => variable_get('agegate_sitemessage'),
    'logoshow'    => variable_get('agegate_logoshow'),
    'logourl'     => theme_get_setting('logo'),
    'buttontext'  => variable_get('agegate_buttontext'),
    'display'     => $display,
    'legalage'    => variable_get('agegate_legalage'),
  );

  drupal_add_js( array('agegate' => $settings), 'setting');
  drupal_add_js(drupal_get_path('module', 'agegate') . '/resources/agegate.js', 'file');
}


/**
* Implements hook_help().
* This is supposed to appear in the Help menu
* There should also be a link in the module page
*/
function agegate_help($path, $arg) {
  switch($path){
    case 'admin/help#agegate':
    {
      $output = '<h3>'.t('About').'</h3>';
      $output += '<p>'.t('This module creates an agegate. Visitors to the site must confirm their age as being over 21 in order to proceed visiting the site.').'</p>';
      return $output;
      break;
    }
  }
}

/**
* Implements hook_permission().
*/

function agegate_permission(){
  return array(
    'admin agegate settings' => array(
      'title' => t('Administrator Agegate'),
      'description' => t('Configure Agegate Options'),
    ),
  );
}

/**
* Imeplements hook_menu().
*/
function agegate_menu(){
  $items = array();

  // Admin Configuration Group
  // When an admin has logged in -- this creates a group
  // under the configuration page.
  $items['admin/config/agegate'] = array(
    'title' => 'Agegate',
    'description' => 'Administer Agegate Options',
    'access arguments' => array('admin agegate settings'),
  );

  // Admin configuration - Settings
  // Adds a link under the Admin Configuration Group
  // mentioned in the above block.
  $items['admin/config/agegate/manage'] = array(
    'title' => 'Agegate Settings',
    'description' => 'Manage Agegate Cart Options and Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agegate_admin_settings_form'),
    'access arguments' => array('admin agegate settings'),
  );

  return $items;
}

/**
* Implements hook_enable().
*/
function agegate_enable(){
  //enable administrators access by defualt
  user_role_grant_permissions(3, array('admin agegate settings'), 'agegate');
}

/**
* Implements hook_form().
*/
function agegate_admin_settings_form($node, &$form_state){
  $form = array();
  $form['overview'] = array(
    '#markup' => t('This interface allows administrators to manage settings for the Agegate.'),
    '#prefix' => '<p>',
    '#suffix' => '</p>'
  );

  // GENERAL
  $form['general'] = array(
    '#title' => t('General Settings'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );
  $form['general']['agegate_sitename'] = array(
    '#title' => t('Website Name'),
    '#description' => t('How would you like your websites name to display on the agegate'),
    '#type' => 'textfield',
    '#default_value' => variable_get('agegate_sitename',variable_get('site_name')),
  );
  $form['general']['agegate_sitemessage'] = array(
    '#title' => t('Legal Message'),
    '#description' => t('Set the legal verbage that the user sees.'),
    '#type' => 'textarea',
    '#default_value' => variable_get(t('agegate_sitemessage'),t('By clicking SUBMIT you verify that you are 21 years of age or older.')),
  );
  $form['general']['agegate_buttontext'] = array(
    '#title' => t('Submit Button Text'),
    '#description' => t('Text of the submit button'),
    '#type' => 'textfield',
    '#default_value' => variable_get(t('agegate_buttontext'),t('Submit')),
  );
  $form['general']['agegate_verifcationtype'] = array(
    '#title' => t('Verifcation Type'),
    '#description' => t('How should the visitor verify their age?'),
    '#type' => 'select',
    '#default_value' => variable_get('agegate_verifcationtype'),
    '#options' => array(
      1 => t('Supply Birthday'),
      2 => t('Answer Question'),
    ),
  );
  $form['general']['agegate_legalage'] = array(
    '#title' => t('Legal Drinking Age'),
    '#description' => t('The legal drinking age to check against.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('agegate_legalage', 21),
  );

  //Display
  $form['enviromentsettings'] = array(
    '#title' => t('Enviroment Settings'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );

  if(isset($_SERVER['PANTHEON_ENVIRONMENT'])){
    $enviroment = $_SERVER['PANTHEON_ENVIRONMENT'];

    switch ($enviroment){
      case 'dev':
      $form['enviromentsettings']['agegate_show'] = array(
        '#title' => t('Show On Dev'),
        '#type' => 'checkbox',
        '#default_value' => variable_get('agegate_show', HIDE),
      );
      $form['enviromentsettings']['agegate_cookiedomain'] = array(
        '#title' => t('Cookie\'s Domain'),
        '#description' => t('Set the DEV domain name that eWinery DEV will use. It is recomended that it be a top level domain.<br />Note: you need not use eWinery in order to use this module.'),
        '#type' => 'textfield',
        '#default_value' => variable_get('agegate_cookiedomain','.domain.com'),
      );
      break;

      case 'test':
      $form['enviromentsettings']['agegate_show'] = array(
        '#title' => t('Show On Test'),
        '#type' => 'checkbox',
        '#default_value' => variable_get('agegate_show', SHOW),
      );
      $form['enviromentsettings']['agegate_cookiedomain'] = array(
        '#title' => t('Cookie\'s Domain'),
        '#description' => t('Set the TEST domain name that eWinery TEST will use. It is recomended that it be a top level domain.<br />Note: you need not use eWinery in order to use this module.'),
        '#type' => 'textfield',
        '#default_value' => variable_get('agegate_cookiedomain','.domain.com'),
      );
      break;

      case 'live':
      $form['enviromentsettings']['agegate_show'] = array(
        '#title' => t('Show On Live'),
        '#type' => 'checkbox',
        '#default_value' => variable_get('agegate_show', SHOW),
        '#disabled' => TRUE,
      );
      $form['enviromentsettings']['agegate_cookiedomain'] = array(
        '#title' => t('Cookie\'s Domain'),
        '#description' => t('Set the LIVE domain name that eWinery LIVE will use. It is recomended that it be a top level domain.<br />Note: you need not use eWinery in order to use this module.'),
        '#type' => 'textfield',
        '#default_value' => variable_get('agegate_cookiedomain','.domain.com'),
      );
      break;
    }
  }
  else{
    $form['enviromentsettings']['agegate_show'] = array(
      '#title' => t('Show On Live'),
      '#type' => 'checkbox',
      '#default_value' => variable_get('agegate_show', SHOW),
    );
    $form['enviromentsettings']['agegate_cookiedomain'] = array(
      '#title' => t('Cookie\'s Domain'),
      '#description' => t('Set the LIVE domain name that eWinery LIVE will use. It is recomended that it be a top level domain.<br />Note: you need not use eWinery in order to use this module.'),
      '#type' => 'textfield',
      '#default_value' => variable_get('agegate_cookiedomain','.domain.com'),
    );
  }

  // LOGO
  $form['logo'] = array(
    '#title' => t('Logo'),
    '#description' => t('Logo specific settings'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed'=> FALSE,
  );
  $form['logo']['agegate_logoshow'] = array(
    '#title' => t('Logo'),
    '#description' => t('Check to display the site logo in the Agegate'),
    '#type' => 'checkbox',
    '#default' => TRUE,
    '#default_value' => variable_get('agegate_logoshow', YES),
  );


  // ADVANCED
  $form['advanced'] = array(
    '#title' => t('Advanced'),
    '#description' => t('Extra settings'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed'=> TRUE,
  );
  $form['advanced']['agegate_debugmode'] = array(
    '#title' => t('Debug mode'),
    '#description' => t('This generates javascript output to the browsers concole. Enabling only affects TEST and DEV enviroments. Also, enabling my cause Internet Explorer to not render the page completly. This is an issue with IE.'),
    '#type' => 'checkbox',
    '#default' => FALSE,
    '#default_value' => variable_get('agegate_debugmode', NO),
  );
  $form['advanced']['agegate_cookiename'] = array(
    '#title' => t('Cookie Name'),
    '#description' => t('Set the cookie name. Ewinery looks for a cookie named "ISLEGAL"' ),
    '#type' => 'textfield',
    '#default_value' => variable_get('agegate_cookiename','ISLEGAL'),
  );

/*
  $form['advanced']['agegate_cookieformat'] = array(
    '#title' => t('Cookie format decoded'),
    '#description' => t('eWinery requires that the cookie be stored in an encoded format. If for some reason you need the cookie stored in a raw format (decoded) check this box.'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('agegate_cookieformat', ENCODED),
  );
*/

  return system_settings_form($form);
}


/**
* Implements hook_form_validate().
*/
function agegate_admin_settings_form_validate($form, &$form_state) {
  //Check that the domain is valid -- we have a very loose definition
  $cookie_domain = $form_state['values']['agegate_cookiedomain'];
  $grep = '/(^\.[A-Za-z0-9\-\_]+)(\.[A-Za-z0-9\-\_]+)+$/';
  if(preg_match($grep, $cookie_domain) == NO){
    form_set_error('agegate_cookiedomain', t('You have added an invalid domain name.'));
  }

  //Check that the domain is valid
  $legal_age = $form_state['values']['agegate_legalage'];
  $grep = '/^[0-9]+$/';
  if(preg_match($grep, $legal_age) == NO){
    form_set_error('agegate_legalage', t('The legal drinking age must be a positive integer.'));
  }
}
